create table test_performance
(
  pk INT GENERATED BY DEFAULT AS IDENTITY,
  testDate date,
  testInteger int,
  testVarchar varchar(10)
);



DECLARE
numberOfTests number := 5;

numberOfIterations number := 100000;

MessageToUser VARCHAR(500) := 'Starting performance test';

overallStartTime TIMESTAMP := CURRENT_TIMESTAMP;
testStartTime TIMESTAMP := CURRENT_TIMESTAMP;
testEndTime TIMESTAMP := CURRENT_TIMESTAMP;
testElapsedTime number := 0;
totalElapsedTime number := 0;
averageElapsedTime number := 0;
testRun number := 1;
iteration number := 1;

BEGIN
WHILE (testRun <= numberOfTests)
LOOP

  iteration := 1;
  testStartTime := CURRENT_TIMESTAMP;

  execute immediate 'truncate table test_performance';
  
  while iteration <= numberOfIterations
  loop
  
    insert into test_performance (testdate, testinteger, testvarchar) values (CURRENT_TIMESTAMP, round(dbms_random.value() *1000,0), 'testString');

    iteration := iteration + 1;

    if (REMAINDER(iteration, 1000) = 0) then
      commit;
    end if;
  end loop;

  
  testRun := testRun + 1;
END LOOP;
END;